[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "reactive-lib/=lib/reactive-lib/src/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
ffi=true
fs_permissions = [
    { access = "read-write", path = "./" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
